# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80b018090d9c1075027ea557c2f1b9a3"
name = "consolidated-order-invoice"
handle = "consolidated-order-invoice"
application_url = "https://synthetic-outlook-forbes-blast.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nobu-checkout-extensibility2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,read_orders,write_products"

[auth]
redirect_urls = [
  "https://synthetic-outlook-forbes-blast.trycloudflare.com/auth/callback",
  "https://synthetic-outlook-forbes-blast.trycloudflare.com/auth/shopify/callback",
  "https://synthetic-outlook-forbes-blast.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
